### ISSUE TITLE
Questions about if this dataset is legal.

### ISSUE THREAD

**Issue by linna21** [git-disl/EllipticPlusPlus#4]
Hello, we are students from the School of Statistics at Renmin University of China. We are currently conducting research using the Elliptic++ dataset. Could you please confirm if this dataset is legal to use? Can we directly cite it in our article? Thank you very much!

**Comment by ll72** [comment]
Yes the paper is published in ACM sigkdd 2023. You can cite it.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: linna21 ***@***.***>
Sent: Tuesday, May 7, 2024 9:13:24 AM
To: git-disl/EllipticPlusPlus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [git-disl/EllipticPlusPlus] Questions about if this dataset is legal. (Issue #4)


Hello, we are students from the School of Statistics at Renmin University of China. We are currently conducting research using the Elliptic++ dataset. Could you please confirm if this dataset is legal to use? Can we directly cite it in our article?
